# Generated by Django 5.2.7 on 2025-12-17 11:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "tin",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="TIN"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="TaxRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_gross_income",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual gross income in PHP",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "allowable_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total allowable deductions in PHP",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_taxable_income",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Gross income minus deductions",
                        max_digits=15,
                    ),
                ),
                (
                    "annual_tax_due",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Computed tax based on TRAIN Law",
                        max_digits=15,
                    ),
                ),
                (
                    "effective_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Effective tax rate as percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_bracket",
                    models.CharField(
                        editable=False, help_text="Income tax bracket", max_length=100
                    ),
                ),
                ("tax_year", models.IntegerField(default=2023)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Most recent record"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Record",
                "verbose_name_plural": "Tax Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_taxrec_user_id_97d1c7_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="core_taxrec_is_acti_a6506d_idx"
                    ),
                ],
            },
        ),
    ]
